"""Shared locale-discovery helpers for docs/<locale>/ folders.

Used by hooks/i18n_status.py (translation-status.md), hooks/split_search_index.py
(per-locale search indexes), and scripts/build_pdfs.py (per-locale PDF export)
-- kept in one place so "which locales exist" and "what counts as full page
coverage" can't drift between the three.
"""

from __future__ import annotations

from pathlib import Path

# Generated by hooks/i18n_status.py itself before every build -- comparing
# it against locales would be comparing the report to itself.
STATUS_FILENAME = "translation-status.md"

# Generated/contributor-only pages that intentionally have no translated
# equivalent in any locale (see docs/en/contributing/index.md's translation
# plan) -- excluded from the English page list these helpers compare against,
# so a locale isn't marked "missing" pages/coverage over content that was
# never meant to be translated in the first place.
UNTRANSLATED_PAGES = {STATUS_FILENAME}


def list_locales(docs_dir: Path) -> list[str]:
    """All docs_dir subdirectories that actually contain Markdown.

    Distinguishes locale folders from shared, non-locale folders living
    alongside them (docs/assets, docs/javascripts, docs/stylesheets).
    """
    return sorted(
        p.name for p in docs_dir.iterdir() if p.is_dir() and any(p.rglob("*.md"))
    )


def en_pages(docs_dir: Path) -> list[str]:
    """English pages (docs_dir-relative paths) that every locale is expected to have."""
    en_dir = docs_dir / "en"
    return sorted(
        p.relative_to(en_dir).as_posix()
        for p in en_dir.rglob("*.md")
        if p.name not in UNTRANSLATED_PAGES
    )


def missing_pages(docs_dir: Path, locale: str, pages: list[str]) -> list[str]:
    """Which of `pages` (as returned by en_pages()) `locale` doesn't have."""
    return [rel for rel in pages if not (docs_dir / locale / rel).exists()]


def fully_covered_locales(docs_dir: Path) -> list[str]:
    """Non-English locales that have every English page (translation-status.md's
    "missing" count is 0) -- doesn't consider staleness, only presence."""
    pages = en_pages(docs_dir)
    return [
        locale
        for locale in list_locales(docs_dir)
        if locale != "en" and not missing_pages(docs_dir, locale, pages)
    ]
