"""Shared locale-discovery helpers for docs/<locale>/ folders.

Used by hooks/i18n_status.py (translation-status.md), hooks/split_search_index.py
(per-locale search indexes), and scripts/build_pdfs.py (per-locale PDF export)
-- kept in one place so "which locales exist" and "what counts as full page
coverage" can't drift between the three.
"""

from __future__ import annotations

from pathlib import Path

# Generated by hooks/i18n_status.py itself before every build -- comparing
# it against locales would be comparing the report to itself.
STATUS_FILENAME = "translation-status.md"

# Generated/contributor-only pages that intentionally have no translated
# equivalent in any locale (see docs/en/contributing/index.md's translation
# plan) -- excluded from the English page list these helpers compare against,
# so a locale isn't marked "missing" pages/coverage over content that was
# never meant to be translated in the first place.
#
# adding-a-language.md is a playbook for whoever bootstraps the *next*
# locale (human or agent) -- contributor-facing, not manual content, same
# category as translation-status.md. Leaving it out of this set silently
# stops every locale from ever reaching "fully covered" (see
# fully_covered_locales(), which gates scripts/build_pdfs.py) since no
# translation of it is ever expected to exist.
#
# SUMMARY.md is the mkdocs-literate-nav plugin's own nav source (see
# mkdocs.yml's plugins: list) -- English-only by design, exactly like the
# YAML nav: block it replaced never had a per-locale copy either. Added
# after the literate-nav migration (which introduced docs/en/SUMMARY.md)
# didn't update this set to match -- the exact silent-never-fully-covered
# failure mode described above, just for a different file: every locale
# was permanently "missing" this one page regardless of real translation
# coverage, which meant fully_covered_locales() always returned []
# (confirmed live: de/es/it all had real content but zero PDF exports).
#
# Matched by bare filename below (see en_pages()), not full path -- same
# convention STATUS_FILENAME already relies on.
UNTRANSLATED_PAGES = {STATUS_FILENAME, "adding-a-language.md", "SUMMARY.md"}


def list_locales(docs_dir: Path) -> list[str]:
    """All docs_dir subdirectories that actually contain Markdown.

    Distinguishes locale folders from shared, non-locale folders living
    alongside them (docs/assets, docs/javascripts, docs/stylesheets).
    """
    return sorted(
        p.name for p in docs_dir.iterdir() if p.is_dir() and any(p.rglob("*.md"))
    )


def en_pages(docs_dir: Path) -> list[str]:
    """English pages (docs_dir-relative paths) that every locale is expected to have."""
    en_dir = docs_dir / "en"
    return sorted(
        p.relative_to(en_dir).as_posix()
        for p in en_dir.rglob("*.md")
        if p.name not in UNTRANSLATED_PAGES
    )


def missing_pages(docs_dir: Path, locale: str, pages: list[str]) -> list[str]:
    """Which of `pages` (as returned by en_pages()) `locale` doesn't have."""
    return [rel for rel in pages if not (docs_dir / locale / rel).exists()]


def fully_covered_locales(docs_dir: Path) -> list[str]:
    """Non-English locales that have every English page (translation-status.md's
    "missing" count is 0) -- doesn't consider staleness, only presence."""
    pages = en_pages(docs_dir)
    return [
        locale
        for locale in list_locales(docs_dir)
        if locale != "en" and not missing_pages(docs_dir, locale, pages)
    ]


# Which locales render their PDF manual via the LaTeX/pandoc pipeline
# (scripts/build_pdf_latex.py) instead of the default Playwright one
# (scripts/build_pdfs.py). A per-locale choice, not a global switch -- French
# is first because it's the locale that already had a LaTeX-based manual in
# the predecessor repo (C:\GitHub\ethos-manual's french/forge/pdf.py) to
# model this on. Add a locale here once its PDF should switch pipelines;
# nothing else needs to change to do so.
PDF_LATEX_LOCALES = {"fr"}


def pdf_build_method(locale: str) -> str:
    """"latex" or "playwright" -- which of the two PDF-export scripts owns
    building this locale's manual. See PDF_LATEX_LOCALES above."""
    return "latex" if locale in PDF_LATEX_LOCALES else "playwright"
